### ISSUE TITLE
Error using Remove-AdminPowerApp in the Microsoft.PowerApps.Administration.PowerShell module

### ISSUE THREAD

**Issue by RickKush** [PowerShell/Community-Blog#115]
I am trying to use `Remove-AdminPowerApp`. I am a PowerPlatform admin, and I am running PowerShell in Administrator mode. The error says: "InvokeApi : The term 'Test-PowerAppsAccount' is not recognized as the name of a cmdlet, function, script file, or
operable program."

When I try to `Install-Module -name Microsoft.PowerApps.Administration.PowerShell`, the error says, "The following commands are already available on this system:'Add-PowerAppsAccount, Get-JwtToken, Get-TenantDetailsFromGraph, Get-UsersOrGroupsFromGraph, InvokeApi, Remove-PowerAppsAccount, ReplaceMacro, Select-CurrentEnvironment, Test-PowerAppsAccount'."

The ISE shows:
![download](https://user-images.githubusercontent.com/116654106/224381045-fa8bd35d-2d7f-43ee-900c-b089acac3e27.png)

**Comment by sdwheeler** [comment]
This repository is for the PowerShell Community blog. You seem to be looking for support for a module. 

It looks like you might not have the latest version of the module installed. When you install the new version, try using the `-AllowClobber` parameter.

If you still have problems, try posting your issue with context in one of the available [community support forums][1].

[1]: https://docs.microsoft.com/powershell/scripting/community/community-support
