### ISSUE TITLE
Update request - How can I copy text to the clipboard

### ISSUE THREAD

**Issue by doctordns** [PowerShell/Community-Blog#12]
The question is how to copy text to the clipboard

# Summary of the update request

- Link to the post in the old blog: https://devblogs.microsoft.com/scripting/can-i-copy-script-output-to-the-clipboard/
- Description of what needs to be changed:
Convert to PowerShell

Should discuss the clipboard and the cmdlets to copy to or from the clipboard.

**Comment by doctorscripto** [comment]
Blog post is written and scheduled to be reviewed
