### ISSUE TITLE
Automated testing of tab completion

### ISSUE THREAD

**Issue by ThomasNieto** [PowerShell/Community-Blog#147]
# Summary of the new document or enhancement

This blog post would contain information about `TabExpansion2` function and how to leverage non-interactive testing of argument completers.

Details of requested document:

- Are you offering to write the post [Y/N]: N
- Proposed title: Automated testing of argument completers
- Links to related posts:
- Description of the problem/scenario/question you want covered:

**Comment by sdwheeler** [comment]
@ThomasNieto This sounds like a good topic. Are you planning to submit it?

**Comment by ThomasNieto** [comment]
@sdwheeler maybe, I'm currently working through this at the moment with my project.

**Comment by sdwheeler** [comment]
Added reference content for [TabExpansion2](https://learn.microsoft.com/powershell/module/microsoft.powershell.core/tabexpansion2)

**Comment by sdwheeler** [comment]
@ThomasNieto I added documentation. But if you have a blog post that tells a useful story about how to use this, I would welcome a post.
