### ISSUE TITLE
Update request - Can I Change the Command Window Title When Running a Script?

### ISSUE THREAD

**Issue by doctordns** [PowerShell/Community-Blog#16]
Update this older Scripting Guys post to the new  blog

# Summary of the update request

- Link to the post in the old blog:
https://devblogs.microsoft.com/scripting/can-i-change-the-command-window-title-when-running-a-script/

- Description of what needs to be changed:
Update to work in PowerShell

**Comment by lightlace** [comment]
It's possible to change the window title with $host.UI.RawUI.WindowTitle

Here is a little code snippet which prompts the user for a new window title string. After the user has entered a string, this string will be used as the new window title.

```
"Testing the change of a PowerShell window title"
$Title = Read-Host -Prompt 'Please enter a new window title '
$Host.UI.RawUI.WindowTitle = $Title
```

**Comment by doctordns** [comment]
This works for the console of both PowerShell and Windows PowerShell. It also works for the Windows PowerShell ISE. It does not work with Terminal or VS Code.

**Comment by lightlace** [comment]
I tried it in Terminal, for me it works 🤔 
![ezgif-1-cef58fb07a83](https://user-images.githubusercontent.com/23658248/110238633-05b1b200-7f43-11eb-9f1b-d7c5bfb21ede.gif)

**Comment by doctordns** [comment]
What I was meaning was that there is not window title for terminal as a whole (C/F the ISE). Ther is, as you point out, a tab title. So the blog post should mention this too!

**Comment by LuanVSO** [comment]
the best/recommended way to do this on all platforms is to use virtual terminal sequences
so like:
```powershell
"Testing the change of a PowerShell window title"
$Title = Read-Host -Prompt 'Please enter a new window title '
write-host "$([char]27)]0;$Title`a" -nonewline
```

**Comment by sdwheeler** [comment]
@LuanVSO Would you like to submit a PR to create this blog post?

**Comment by LuanVSO** [comment]
not really comfortable writing a blog post as English is not my first language, but I'm happy to provide the code.

**Comment by doctordns** [comment]
I have been out of the lop a bit over the past 6 months - lost my mother late last year and the fall out has been hard to deal with. I kind of lost my enthusiasm for most things. But after a brief trip to the home country, I feel much better. With that said...

Please consider having a go at this. If English is an issue: a) use google translate and b) leave the rest to me!  I will happily do the editing for you to get your post out!  Contact me privately and we can create the PR for you to issue.

**Comment by mikeegan400** [comment]
@doctordns Is ghost-writing allowed?  I could write the post and @LuanVSO could submit it under their name.

**Comment by doctorscripto** [comment]
I don't know if we have any rules AGAINST Ghost Writing.    I thinks it's all about the authors getting their due credit.   Collaboration should not be an issue I would think.   What do all think?

Cheers!

Sean Kearney
He/Him
CSA-Engineer
COGS Apps Infra Support
Office: 613.212.2382
Mobile: 613.852.8721
***@***.******@***.***>

[Microsoft Logo]

[Icon For Twitter linking to Sean's Twitter Account]<https://twitter.com/powershellman>   [Icon for Facebook linking to Sean's Facebook Profile] <https://www.facebook.com/powershellman/>    [Icon for LinkedIn pointing to Sean's profile on LinkedIn] <https://www.linkedin.com/in/seankearney/>    [Icon for Youtube with link to Sean's Bad singing on Youtube] <https://www.youtube.com/user/ye110wbeard>

**Comment by sdwheeler** [comment]
Ghostwriting goes against the spirit and intent of the blog. But you can both get credit for the post. Let me know if you submit a PR and want to credit both authors.

**Comment by doctordns** [comment]
I have been absent here of late due to health reasons, so apologies for the recent lack of input.
Sean makes a great point. If anyone wants to write a post, we can help. But it is their article. If two/three want to collaborate, well, I suppose, but I'd prefer each post have a single author. By all means you (SK) can help others to get the tone and contents right.

**Comment by FranciscoNabas** [comment]
If it's still available I'd like to take a shot at this post. Of course giving credit to @LuanVSO

**Comment by sdwheeler** [comment]
@FranciscoNabas go for it.
