### ISSUE TITLE
Labels configured in Issue Templates but not set up

### ISSUE THREAD

**Issue by PsychoData** [PowerShell/Community-Blog#22]
`post-idea` and `idea` labels are not setup in https://github.com/PowerShell/Community-Blog/labels 
but are referenced in [New_Post_Idea,md](https://github.com/PowerShell/Community-Blog/blob/main/.github/ISSUE_TEMPLATE/New_Post_Idea.md) (`idea`)   and [Request_Update.md](https://github.com/PowerShell/Community-Blog/blob/main/.github/ISSUE_TEMPLATE/Request_Update.md) (`post-idea`)

Need someone with write-access to make these labels so that the issues can start getting created with them, and fix the labels on the previously created issues, preferably before the other issues get too buried

**Comment by sdwheeler** [comment]
Thanks. This is still a work in progress. But I added these two labels.
