### ISSUE TITLE
Post idea: Permanent Event Handling using Windows WMI and PowerShell

### ISSUE THREAD

**Issue by farismalaeb** [PowerShell/Community-Blog#60]
# Summary of the new document or enhancement

Details of requested document:

- Are you offering to write the post [Y/N]: Y
- Proposed title: Permanent Event Handling using Windows WMI and PowerShell
- Links to related posts:
- Description of the problem/scenario/question you want covered: 
This article goes through the steps required to create a permanent WMI event Handling.
I used Windows Services Win32_Service as an example and also Win32_Share.
The Cmdlets are the CIM cmdlets, also I show the case using PowerShell 7.
I try to explain EventFilter, all Consumers classes, and Binding and provide multiple examples.
Also explained how to write the WMI Filter

**Comment by doctordns** [comment]
We have just published an article on this subject: [How Do I Discover Changes to an AD Group’s Membership](https://devblogs.microsoft.com/powershell-community/how-do-i-discover-changes-to-an-ad-groups-membership/). That article looks at permanent event handling in the context of AD groups.

I am not sure we need another one just yet so I am closing this issue with thanks.  As an alternative, why not refocus your suggested article to cover temporary eventing? I had intended to write a follow article on that and please post a post idea issue here. 

Thanks.
