### ISSUE TITLE
Restart-computer does not work in VS code

### ISSUE THREAD

**Issue by jensenjk** [PowerShell/Community-Blog#94]
When  executing this from powershell console og ISE it works - script wait for vmi and then for powershell connectivity

Restart-Computer -Wait -ComputerName $computer -Force

When executing the command from VS Code the computer restarts, and check for VMI is OK but the check for powershell connectivity never completes unless setting -timeout - then the statement times out.

**Comment by sdwheeler** [comment]
@jensenjk This sounds like a support question/issue, not a comment about a blog post.

This is not the right forum for these kind of questions. 
Try posting your problem in a community support forum. 
For a list of community forums see: https://docs.microsoft.com/powershell/scripting/community/community-support
