### ISSUE TITLE
Password Expiry Notification Using Teams and Graph API

### ISSUE THREAD

**Issue by farismalaeb** [PowerShell/Community-Blog#95]
# Summary of the new document or enhancement

Details of requested document:

- Are you offering to write the post [Y/N]: Y
- Proposed title: Password Expiry Notification Using Teams and Graph API
- Links to related posts: https://www.powershellcenter.com/2022/07/15/new-mgchat/
- Description of the problem/scenario/question you want covered:
The post is a demo on how to use Microsoft Graph to send Emails and Teams Message using Graph API.

**Comment by doctordns** [comment]
I've not been very busy on this blog, of late. I have had some personal issues and am slowly resolving the worst of the issues , but I am, as the saying goes, living in interesting times. Anyway...

This sounds a great idea. Some things I'd like to ensure you cover:
1. What IS the Graph API (in a few sentences) with pointerrs to more detail.
2. What do you use it for? 
3. Where do you get the module(s).
4. How do you use it?

Let's see an outline or a draft!

**Comment by farismalaeb** [comment]
Super, will start working on it this week

**Comment by sdwheeler** [comment]
Closed by #96
